[theme] 
primaryColor="#4b0082" 
backgroundColor="#f0f0f5" 
secondaryBackgroundColor="#e0e0ef" 
textColor="#262730"
dataframeHeaderBackgroundColor='#dee1f3ff'

[runner]
fastReruns = true

[global]
showWarningOnDirectExecution = false

[client]
showErrorDetails = "none"
